### ISSUE TITLE
Leech settings and thumbnails not persistent

### ISSUE THREAD

**Issue by hehenaice** [iamLiquidX/MirLeechX#10]
I understand you aren't providing any support for this repo, but would be great if you could direct me towards a way I could fix it myself. 
Currently running it on a private server and anytime I restart it, it's leech settings and thumbnails are gone.
And that's prolly not how it's supposed to be lol.

**Comment by iamLiquidX** [comment]
> I understand you aren't providing any support for this repo, but would be great if you could direct me towards a way I could fix it myself. Currently running it on a private server and anytime I restart it, it's leech settings and thumbnails are gone. And that's prolly not how it's supposed to be lol.

Restart command is supposed to do that. Since u running this in private server , u must be running it in docker , so everytime u restart it it clears the whole docker files and restarts it. 
Have you provided database_url variable, if not , try providing it.

**Comment by hehenaice** [comment]
Yep having a postgres server running on the same server.
Tried spawning it on a separate instance.
Yet
Doesn't seem to save it to the database sadly

**Comment by iamLiquidX** [comment]
> Yep having a postgres server running on the same server. Tried spawning it on a separate instance. Yet Doesn't seem to save it to the database sadly

i will look into it, but no promises.

**Comment by hehenaice** [comment]
> i will look into it, but no promises.

Understandable
I'm humbled by your response itself

**Comment by iamLiquidX** [comment]
> > i will look into it, but no promises.
> 
> Understandable I'm humbled by your response itself

https://github.com/anasty17/mirror-leech-telegram-bot
Original dev is back. You can report the bug to him. He is actively working on it so you won't have to wait long.
